#!/usr/bin/env python

import moveit_commander
from sensor_msgs.msg import JointState


def main():
    move = moveit_commander.MoveGroupCommander('arm')
    move.set_max_velocity_scaling_factor(0.1)

    move.set_named_target('ready')
    move.go()

    js1= JointState()
    js1.name= [
        "arm_elbow_joint",
        "arm_shoulder_lift_joint",
        "arm_shoulder_pan_joint",
        "arm_wrist_1_joint",
        "arm_wrist_2_joint",
        "arm_wrist_3_joint"
        ]
    js1.position=[
        -0.8247761130332947,
        -2.128296037713522,
        -2.37681490579714,
        -3.01825012783193,
        0.7835541367530823,
        -4.93801457086672
        ]
    move.set_joint_value_target(js1)
    move.set_max_velocity_scaling_factor(1.0)
    move.go()

if __name__ =="__main__":
    main()